import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import {
  sha256, verifySecurity, verifyBootSelector, verifiedRead,
  validateManifest, validateArtifact,
} from "../src/guards.js";

const hash = bytes => createHash("sha256").update(bytes).digest("hex");
const digest = bytes => new Uint8Array(createHash("md5").update(bytes).digest());
function manifest() {
  return {
    schema_version: 1, build_id: "conference-factory-3",
    hardware: { chip: "esp32s3", flash_bytes: 16777216, psram_bytes: 8388608 },
    flash: { erase_all: false, requires_partition_match: true },
    partition_table: { offset: 0x8000, sector_size: 4096, sector_sha256: "a".repeat(64) },
    artifacts: [
      { offset: 0, size_bytes: 22272, path: "bootloader.bin", sha256: "1".repeat(64) },
      { offset: 0x8000, size_bytes: 3072, path: "partition-table.bin", sha256: "2".repeat(64) },
      { offset: 0x10000, size_bytes: 1676960, path: "application.bin", sha256: "3".repeat(64) },
    ],
  };
}
function security(flags = 0, crypt = 0, chip = 9) {
  const bytes = new Uint8Array(20), view = new DataView(bytes.buffer);
  view.setUint32(0, flags, true); bytes[4] = crypt; view.setUint32(12, chip, true);
  return bytes;
}
// Captured from the documented native IDF bootstrap shape, not generated by the guard.
// CRC = binascii.crc32(struct.pack('<I', 1), 0xffffffff).
function bootSelector() {
  const bytes = new Uint8Array(8192).fill(255);
  bytes.set(Buffer.from("01000000ffffffffffffffffffffffffffffffffffffffff020000009a984347", "hex"));
  return bytes;
}
function legacyBootSelector() {
  const bytes = new Uint8Array(8192).fill(255);
  bytes.set(Buffer.from("01000000ffffffffffffffffffffffffffffffffffffffffffffffff9a984347", "hex"));
  bytes.set(Buffer.from("00000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "hex"), 4096);
  return bytes;
}

test("security checks reject protected and unidentified chips before writes", () => {
  for (const flags of [0, 1 << 6, 1 << 7]) assert.doesNotThrow(() => verifySecurity(security(flags)));
  for (const flags of [1, 4, 5, 0xffffffff]) assert.throws(() => verifySecurity(security(flags)), /Nothing was written/);
  for (const count of [1, 2, 4, 7, 0x80]) assert.throws(() => verifySecurity(security(0, count)), /Nothing was written/);
  for (const count of [0, 3, 5, 6, 255]) assert.doesNotThrow(() => verifySecurity(security(0, count)));
  for (const chip of [0, 2, 6, 8, 10, 0xffffffff]) assert.throws(() => verifySecurity(security(0, 0, chip)));
  for (const value of [null, {}, [], new Uint8Array(19), new Uint8Array(21)]) assert.throws(() => verifySecurity(value));
  const padded = new Uint8Array(40).fill(0xab); padded.set(security(), 7);
  assert.doesNotThrow(() => verifySecurity(padded.subarray(7, 27)), "respect a typed-array byte offset");
});

test("boot guard accepts only erased or exact first-boot app0 selector", () => {
  assert.doesNotThrow(() => verifyBootSelector(new Uint8Array(8192).fill(255)));
  assert.doesNotThrow(() => verifyBootSelector(bootSelector()));
  for (const position of [0, 4, 24, 28, 31, 32, 4095, 4096, 8191]) {
    const altered = bootSelector(); altered[position] ^= 1;
    assert.throws(() => verifyBootSelector(altered), /Nothing was written/, `reject mutation at ${position}`);
  }
  for (const state of [0, 1, 3, 4, 0xffffffff]) {
    const bytes = bootSelector(); new DataView(bytes.buffer).setUint32(24, state, true);
    assert.throws(() => verifyBootSelector(bytes), /different boot-selection/);
  }
  for (const length of [0, 4096, 8191, 8193]) assert.throws(() => verifyBootSelector(new Uint8Array(length).fill(255)), /Incomplete/);
});

test("boot guard also accepts the exact pinned Arduino upload selector without changing it", () => {
  const bytes = legacyBootSelector();
  // Matches both the installed core's file and official tagged upstream binary.
  // https://github.com/espressif/arduino-esp32/blob/3.3.10/tools/partitions/boot_app0.bin
  assert.equal(hash(bytes), "f94c5d786a7a8fab06ac5d10e33bf37711a6697636dc037559ea19cc410a17f0");
  const before = bytes.slice();
  assert.doesNotThrow(() => verifyBootSelector(bytes));
  assert.deepEqual(bytes, before, "the check never rewrites OTA metadata");
  for (const position of [0, 1, 4, 23, 24, 28, 31, 32, 4095, 4096, 4100, 4120, 4124, 4127, 4128, 8191]) {
    const altered = bytes.slice(); altered[position] ^= 1;
    assert.throws(() => verifyBootSelector(altered), /Nothing was written/, `reject legacy mutation at ${position}`);
  }
  const hybrid = bytes.slice(); hybrid.fill(255, 4096);
  assert.throws(() => verifyBootSelector(hybrid), /different boot-selection/, "do not admit unverified combinations of the fixtures");
});

test("verifiedRead consumes the raw MD5 trailer before a later command", async () => {
  const bytes = Uint8Array.from({ length: 8192 }, (_, i) => i % 256);
  const events = [];
  const loader = { async readFlash(offset, size) { events.push(["data", offset, size]); return bytes; } };
  const transport = { async read(timeout) { events.push(["digest", timeout]); return digest(bytes); } };
  assert.equal(await verifiedRead(loader, transport, 0xe000, 8192), bytes);
  events.push(["next command"]);
  assert.deepEqual(events, [["data", 0xe000, 8192], ["digest", 3000], ["next command"]]);
});

test("verifiedRead rejects truncation, digest corruption, and missing trailers", async () => {
  const bytes = new Uint8Array(4096).fill(255);
  const corrupted = digest(bytes); corrupted[9] ^= 1;
  for (const trailer of [undefined, null, [], new Uint8Array(15), new Uint8Array(17), corrupted]) {
    await assert.rejects(verifiedRead({ readFlash: async () => bytes }, { read: async () => trailer }, 0x8000, 4096), /USB read verification failed/);
  }
  let consumed = false;
  await assert.rejects(verifiedRead({ readFlash: async () => bytes.subarray(0, 4095) }, {
    read: async () => { consumed = true; return digest(bytes.subarray(0, 4095)); },
  }, 0x8000, 4096), /USB read verification failed/);
  assert.equal(consumed, true, "drain trailer even when byte count is wrong");
  await assert.rejects(verifiedRead({ readFlash: async () => bytes }, { read: async () => { throw Error("transport timeout"); } }, 0, 4096), /transport timeout/);
});

test("manifest requires the exact hardware and preservation contract", () => {
  const good = manifest(); assert.equal(validateManifest(good), good);
  for (const key of ["schema_version", "build_id", "hardware", "flash", "partition_table", "artifacts"]) {
    const value = manifest(); delete value[key]; assert.throws(() => validateManifest(value), key);
  }
  for (const mutate of [
    m => m.schema_version = "1", m => m.build_id = "conference-factory-99",
    m => m.hardware.chip = "esp32", m => m.hardware.flash_bytes = 8388608,
    m => m.hardware.psram_bytes = 0, m => m.flash.erase_all = true,
    m => m.flash.requires_partition_match = false, m => m.partition_table.offset = 0x9000,
    m => m.partition_table.sector_size = 3072, m => m.partition_table.sector_sha256 = "a".repeat(63),
  ]) { const value = manifest(); mutate(value); assert.throws(() => validateManifest(value)); }
  for (const value of [null, undefined, [], {}, true]) assert.throws(() => validateManifest(value));
});

test("manifest blocks data-partition writes, gaps, duplicates, oversized images, and foreign paths", () => {
  for (const offset of [0x9000, 0xe000, 0x310000, 0x610000, 0xff0000, -1, 0.5, "65536"]) {
    const value = manifest(); value.artifacts[2].offset = offset;
    assert.throws(() => validateManifest(value), `offset ${offset}`);
  }
  for (const mutate of [
    m => m.artifacts.pop(), m => m.artifacts.push({ ...m.artifacts[2] }),
    m => m.artifacts[2].offset = 0, m => m.artifacts[0].size_bytes = 0x8001,
    m => m.artifacts[1].size_bytes = 4097, m => m.artifacts[2].size_bytes = 0x300001,
  ]) { const value = manifest(); mutate(value); assert.throws(() => validateManifest(value)); }
  for (const size of [0, -1, 1.5, "123", NaN, Infinity]) {
    const value = manifest(); value.artifacts[2].size_bytes = size; assert.throws(() => validateManifest(value));
  }
  for (const path of ["../app.bin", "/app.bin", "https://other.test/app.bin", "app.bin?x=1", "app.bin#x", "app%2f.bin", "app.bin\n", "APP.bin"]) {
    const value = manifest(); value.artifacts[2].path = path; assert.throws(() => validateManifest(value), path);
  }
  const missingHash = manifest(); delete missingHash.artifacts[1].sha256;
  assert.throws(() => validateManifest(missingHash));
});

test("download verification detects altered content and declared lengths", async () => {
  const bytes = new Uint8Array([0xe9, 0x03, 0x02, 0x4f, 0x00]);
  assert.equal(await sha256(bytes), hash(bytes));
  const artifact = { size_bytes: bytes.length, sha256: hash(bytes) };
  await assert.doesNotReject(validateArtifact(artifact, bytes));
  const changed = bytes.slice(); changed[4] ^= 1;
  await assert.rejects(validateArtifact(artifact, changed), /did not pass verification/);
  await assert.rejects(validateArtifact({ ...artifact, size_bytes: bytes.length + 1 }, bytes), /did not pass verification/);
});
