#!/usr/bin/env python3
"""Embed the supplied conference shader loop using LVGL's native GIF decoder.

The original video stays outside Git. Requires FFmpeg/ffprobe; output GIF and
inspection frames stay under .build/, while the flash-resident C asset is tracked.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCE_SHA256 = "0f8d8810a6d83dd553116e0f64f645df467281d6a2962f50307d97d2e527dbd2"
# This inspected FFmpeg 9.0.1 output has one shared global palette and no local
# palettes. Pin it before changing the background entry: compressed pixels,
# frame rectangles, transparency and delays must remain byte-for-byte intact.
CONVERTED_SHA256 = "c3e99e61b4f24b349e9f64cbc58f4ef4e57c83488396aa803da5955a9bde7cb4"
FILTER = (
    "crop=ih*468/466:ih,scale=468:466:flags=lanczos,fps=6,split[a][b];"
    "[a]palettegen=max_colors=8:reserve_transparent=1:stats_mode=diff[p];"
    "[b][p]paletteuse=dither=none:diff_mode=rectangle"
)


def probe(path):
    return json.loads(subprocess.check_output([
        "ffprobe", "-v", "error", "-count_frames", "-select_streams", "v:0",
        "-show_entries", "stream=width,height,duration,nb_read_frames", "-of", "json", str(path)
    ]))["streams"][0]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="Original shader-recording-1786483880341.mp4")
    args = parser.parse_args()
    if hashlib.sha256(args.source.read_bytes()).hexdigest() != SOURCE_SHA256:
        parser.error("Source does not match the user-provided shader recording.")
    original = probe(args.source)
    if (original["width"], original["height"], original["nb_read_frames"], original["duration"]) != (3836, 2156, "600", "10.000000"):
        parser.error("Unexpected source dimensions, frame count or duration.")
    out = ROOT / ".build/design-loop"
    out.mkdir(parents=True, exist_ok=True)
    gif = out / "intro_loop.gif"
    subprocess.run([
        "ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(args.source),
        "-filter_complex", FILTER, "-an", "-loop", "0", str(gif)
    ], check=True)
    decoded = probe(gif)
    if (decoded["width"], decoded["height"], decoded["nb_read_frames"], decoded["duration"]) != (468, 466, "60", "10.000000"):
        raise RuntimeError("GIF conversion changed the expected frame count or full loop duration")
    data = gif.read_bytes()
    if hashlib.sha256(data).hexdigest() != CONVERTED_SHA256:
        raise RuntimeError("FFmpeg conversion changed; inspect its palettes before updating the black correction")
    if data[:6] != b"GIF89a" or not (data[10] & 0x80) or data[13:16] != bytes((17, 16, 18)):
        raise RuntimeError("Unexpected GIF background palette entry")
    # The shared darkest shade is the source's near-black background. Change
    # only that RGB triplet; avoid re-quantizing the fine animated cross pattern.
    data = data[:13] + bytes(3) + data[16:]
    gif.write_bytes(data)
    if len(data) > 800 * 1024:
        raise RuntimeError("GIF exceeds the bounded flash asset budget")
    digest = hashlib.sha256(data).hexdigest()
    generated = [
        "// Generated by scripts/generate-intro-loop.py; do not edit.",
        "// Source SHA-256: " + SOURCE_SHA256,
        "// GIF SHA-256: " + digest,
        "// 468 x 466, 60 frames, 10 seconds, pure black + six shades + transparency.",
        '#include "intro_loop.h"',
        "static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t intro_loop_data[] = {",
    ]
    for start in range(0, len(data), 20):
        generated.append("    " + ",".join(f"0x{value:02x}" for value in data[start:start + 20]) + ",")
    generated.extend([
        "};",
        "const lv_image_dsc_t intro_loop = {",
        "    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RAW, .w = 468, .h = 466 },",
        "    .data_size = sizeof(intro_loop_data),",
        "    .data = intro_loop_data,",
        "};", ""
    ])
    (ROOT / "firmware/factory_badge/main/ui/intro_loop.c").write_text("\n".join(generated))
    print(f"Embedded {len(data)} bytes; 60 frames / 10 seconds; SHA-256 {digest}")


if __name__ == "__main__":
    main()
