#!/usr/bin/env python3
"""Package the supplied init() marks as LVGL alpha images without resampling.

Requires Pillow. Sources are the PNG exports in ui/assets; RGB marks are
white, so their original alpha coverage (including 50% small logo) is preserved.
The outlined bookmark retains its exact source coverage, with the card backdrop removed.
The fixed Hack QR retains the verified supplied export's original modules.
"""
import argparse
import hashlib
from pathlib import Path
from PIL import Image, ImageChops
ROOT = Path(__file__).resolve().parents[1]
UI = ROOT / 'firmware/factory_badge/main/ui'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--source-designs', type=Path,
                    help='Re-extract the fixed Hack QR and outline bookmark from supplied designs.')
args = parser.parse_args()
if args.source_designs:
    source_path = args.source_designs / 'Make it yours.png'
    source_hash = hashlib.sha256(source_path.read_bytes()).hexdigest()
    if source_hash != '8edb37c71befd7cf98c248c94e05b7770e3ff4edc95e20ef2c2ef09bb2a59ad5':
        raise SystemExit('The supplied Make it yours.png checksum does not match.')
    # Native source pixels, including its quiet zone and edge antialiasing.
    qr = Image.open(source_path).convert('RGB').crop((122, 138, 344, 360))
    red, green, blue = qr.split()
    if ImageChops.difference(red, green).getbbox() or ImageChops.difference(green, blue).getbbox():
        raise SystemExit('The supplied Hack QR must be monochrome.')
    mask = Image.new('RGBA', qr.size, (255, 255, 255, 255))
    mask.putalpha(qr.convert('L'))
    mask.save(UI / 'assets' / 'hack_qr.png')
    source_path = args.source_designs / 'Group 2147219341.png'
    source_hash = hashlib.sha256(source_path.read_bytes()).hexdigest()
    if source_hash != '5e0d5dc6b7e9ec9c684229e6102ad4c63b50f4b9f3361f8d9cec4ac8a1cfe2dd':
        raise SystemExit('The supplied Group 2147219341.png checksum does not match.')
    outline = Image.open(source_path).convert('RGB').crop((228, 14, 257, 43))
    red, green, blue = outline.split()
    if (ImageChops.difference(red, green).getbbox() or
            ImageChops.difference(green, blue).getbbox() or red.getextrema()[0] < 22):
        raise SystemExit('The outline bookmark must be white over its #161616 card.')
    # Reverse the source's white-over-#161616 composite. This reconstructs every
    # original channel exactly when alpha is composited over that same card.
    alpha = red.point(lambda c: round((c - 22) * 255 / 233))
    mask = Image.new('RGBA', outline.size, (255, 255, 255, 255))
    mask.putalpha(alpha)
    mask.save(UI / 'assets' / 'bookmark_outline.png')
NAMES = ['logo_small', 'logo_large', 'left', 'right', 'bookmark', 'bookmark_outline',
         'empty_portrait', 'hack_qr']
assets = []
for name in NAMES:
    image = Image.open(UI / 'assets' / (name + '.png')).convert('RGBA')
    alpha = image.getchannel('A')
    assets.append((name, alpha))
header = '#pragma once\n#include <lvgl.h>\nnamespace badge::ui {\n'
header += 'inline constexpr char supplied_hack_qr_url[] = "https://drop.workos.cloud/stopwatch";\n'
source = '// Generated by scripts/generate-design-assets.py; do not edit.\n#include "design_assets.h"\nnamespace badge::ui {\n'
for name, alpha in assets:
    symbol = 'supplied_' + name
    header += f'extern const lv_image_dsc_t {symbol};\n'
    values = list(alpha.tobytes())
    source += f'static const uint8_t {symbol}_pixels[] = {{\n'
    source += ''.join('  '+','.join(str(v) for v in values[i:i+32])+',\n' for i in range(0,len(values),32))
    w,h = alpha.size
    source += f'''}};
const lv_image_dsc_t {symbol} = [] {{
    lv_image_dsc_t image{{}};
    image.header.magic = LV_IMAGE_HEADER_MAGIC;
    image.header.cf = LV_COLOR_FORMAT_A8;
    image.header.w = {w}; image.header.h = {h}; image.header.stride = {w};
    image.data_size = sizeof({symbol}_pixels); image.data = {symbol}_pixels;
    return image;
}}();
'''
(UI/'design_assets.h').write_text(header + '} // namespace badge::ui\n')
(UI/'design_assets.cpp').write_text(source + '} // namespace badge::ui\n')
