#!/usr/bin/env python3
"""Package the supplied init() marks as LVGL alpha images without resampling.

Requires Pillow. Sources are the five PNG exports in ui/assets; RGB marks are
white, so their original alpha coverage (including 50% small logo) is preserved.
The outlined bookmark is the one-pixel inner edge of the supplied silhouette.
"""
from pathlib import Path
from PIL import Image, ImageChops, ImageFilter
ROOT = Path(__file__).resolve().parents[1]
UI = ROOT / 'firmware/factory_badge/main/ui'
NAMES = ['logo_small', 'logo_large', 'left', 'right', 'bookmark', 'empty_portrait']
assets = []
for name in NAMES:
    image = Image.open(UI / 'assets' / (name + '.png')).convert('RGBA')
    alpha = image.getchannel('A')
    assets.append((name, alpha))
    if name == 'bookmark':
        assets.append(('bookmark_outline', ImageChops.subtract(alpha, alpha.filter(ImageFilter.MinFilter(3)))))
header = '#pragma once\n#include <lvgl.h>\nnamespace badge::ui {\n'
source = '// Generated by scripts/generate-design-assets.py; do not edit.\n#include "design_assets.h"\nnamespace badge::ui {\n'
for name, alpha in assets:
    symbol = 'supplied_' + name
    header += f'extern const lv_image_dsc_t {symbol};\n'
    values = list(alpha.tobytes())
    source += f'static const uint8_t {symbol}_pixels[] = {{\n'
    source += ''.join('  '+','.join(str(v) for v in values[i:i+32])+',\n' for i in range(0,len(values),32))
    w,h = alpha.size
    source += f'''}};
const lv_image_dsc_t {symbol} = [] {{
    lv_image_dsc_t image{{}};
    image.header.magic = LV_IMAGE_HEADER_MAGIC;
    image.header.cf = LV_COLOR_FORMAT_A8;
    image.header.w = {w}; image.header.h = {h}; image.header.stride = {w};
    image.data_size = sizeof({symbol}_pixels); image.data = {symbol}_pixels;
    return image;
}}();
'''
(UI/'design_assets.h').write_text(header + '} // namespace badge::ui\n')
(UI/'design_assets.cpp').write_text(source + '} // namespace badge::ui\n')
